### PR TITLE
remove useless flag

### PR DESCRIPTION
**Pull request by fahedouch**
Signed-off-by: fahedouch <fahed.dorgaa@gmail.com>

### CODE REVIEW

**Comment by tianon** [comment]
What harm does the flag cause?

**Comment by fahedouch** [comment]
> What harm does the flag cause?

I can't see the `-T` flag in the `man cp` , it fails when running on my mac.

**Comment by kolbma** [comment]
This is only available in the cp from GNU coreutils.
```
       -T, --no-target-directory
              treat DEST as a normal file
```

**Comment by tianon** [comment]
Sorry, I don't have a mac and don't use a mac (also, this is an extremely Linux-centric utility, so anyone trying to test it or implementations of it, which is the intent of this script, should probably be on Linux as well). :bow: :heart:

**Pull request closed without merging**
